// <auto-generated />
namespace Global_Cinema.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class movemigrator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(movemigrator));
        
        string IMigrationMetadata.Id
        {
            get { return "202211192050292_move-migrator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
